config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :aa_articles
  resources :a_articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/a_article.rb
class AArticle < ApplicationRecord
end

app/models/aa_article.rb
class AaArticle < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/a_articles_controller.rb
class AArticlesController < ApplicationController
  before_action :set_a_article, only: [:show, :edit, :update, :destroy]

  # GET /a_articles
  def index
    @a_articles = AArticle.all
  end

  # GET /a_articles/1
  def show
  end

  # GET /a_articles/new
  def new
    @a_article = AArticle.new
  end

  # GET /a_articles/1/edit
  def edit
  end

  # POST /a_articles
  def create
    @a_article = AArticle.new(a_article_params)

    if @a_article.save
      redirect_to @a_article, notice: 'A article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /a_articles/1
  def update
    if @a_article.update(a_article_params)
      redirect_to @a_article, notice: 'A article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /a_articles/1
  def destroy
    @a_article.destroy
    redirect_to a_articles_url, notice: 'A article was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_a_article
      @a_article = AArticle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def a_article_params
      params.require(:a_article).permit(:title, :body)
    end
end

app/controllers/aa_articles_controller.rb
class AaArticlesController < ApplicationController
  before_action :set_aa_article, only: [:show, :edit, :update, :destroy]

  # GET /aa_articles
  def index
    @aa_articles = AaArticle.all
  end

  # GET /aa_articles/1
  def show
  end

  # GET /aa_articles/new
  def new
    @aa_article = AaArticle.new
  end

  # GET /aa_articles/1/edit
  def edit
  end

  # POST /aa_articles
  def create
    @aa_article = AaArticle.new(aa_article_params)

    if @aa_article.save
      redirect_to @aa_article, notice: 'Aa article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /aa_articles/1
  def update
    if @aa_article.update(aa_article_params)
      redirect_to @aa_article, notice: 'Aa article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /aa_articles/1
  def destroy
    @aa_article.destroy
    redirect_to aa_articles_url, notice: 'Aa article was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aa_article
      @aa_article = AaArticle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aa_article_params
      params.require(:aa_article).permit(:title, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/helpers/a_articles_helper.rb
module AArticlesHelper
end

app/helpers/aa_articles_helper.rb
module AaArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/a_articles/_form.html.erb
<%= form_with(model: a_article) do |form| %>
  <% if a_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(a_article.errors.count, "error") %> prohibited this a_article from being saved:</h2>

      <ul>
        <% a_article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/a_articles/edit.html.erb
<h1>Editing A Article</h1>

<%= render 'form', a_article: @a_article %>

<%= link_to 'Show', @a_article %> |
<%= link_to 'Back', a_articles_path %>

app/views/a_articles/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Pagina de Inicio</h1>
<h1>A Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @a_articles.each do |a_article| %>
      <tr>
        <td><%= a_article.title %></td>
        <td><%= a_article.body %></td>
        <td><%= link_to 'Show', a_article %></td>
        <td><%= link_to 'Edit', edit_a_article_path(a_article) %></td>
        <td><%= link_to 'Destroy', a_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New A Article', new_a_article_path %>

app/views/a_articles/new.html.erb
<h1>New A Article</h1>

<%= render 'form', a_article: @a_article %>

<%= link_to 'Back', a_articles_path %>

app/views/a_articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @a_article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @a_article.body %>
</p>

<%= link_to 'Edit', edit_a_article_path(@a_article) %> |
<%= link_to 'Back', a_articles_path %>

app/views/aa_articles/_form.html.erb
<%= form_with(model: aa_article) do |form| %>
  <% if aa_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aa_article.errors.count, "error") %> prohibited this aa_article from being saved:</h2>

      <ul>
        <% aa_article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aa_articles/edit.html.erb
<h1>Editing Aa Article</h1>

<%= render 'form', aa_article: @aa_article %>

<%= link_to 'Show', @aa_article %> |
<%= link_to 'Back', aa_articles_path %>

app/views/aa_articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aa Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aa_articles.each do |aa_article| %>
      <tr>
        <td><%= aa_article.title %></td>
        <td><%= aa_article.body %></td>
        <td><%= link_to 'Show', aa_article %></td>
        <td><%= link_to 'Edit', edit_aa_article_path(aa_article) %></td>
        <td><%= link_to 'Destroy', aa_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aa Article', new_aa_article_path %>

app/views/aa_articles/new.html.erb
<h1>New Aa Article</h1>

<%= render 'form', aa_article: @aa_article %>

<%= link_to 'Back', aa_articles_path %>

app/views/aa_articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @aa_article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @aa_article.body %>
</p>

<%= link_to 'Edit', edit_aa_article_path(@aa_article) %> |
<%= link_to 'Back', aa_articles_path %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>